# Tárgyankénti beállítások (Anyag neve: "érték")
# Ha negatív számot adsz meg, az csökkenti a sebzést.
modifiers:
  DIAMOND_SWORD: "2.0"
  NETHERITE_SWORD: "25%"
  WOODEN_SWORD: "-50%"
  HAND: "-1.0"

# Poti effektek (szintenként értendő módosítás)
potions:
  # Ha Strength II van rajtad, ez kétszer adódik hozzá
  STRENGTH_MODIFIER: "1.5"
