# Globális módosító, minden számítás végén fut le
# "0.0" = nincs változás, "10%" = minden sebzés +10%
overall_modifier: "0.0"

# Tárgyankénti beállítások
modifiers:
  DIAMOND_SWORD: "2.0"
  NETHERITE_SWORD: "25%"
  HAND: "-1.0"

# Bűvölések
enchantments:
  # Alapértelmezett érték (szintenként adódik hozzá, ha nincs specifikus szint)
  SHARPNESS: "0.5"
  # Specifikus szintek (ha ezt megadod, nem az alapot használja)
  SHARPNESS_5: "5.0"

# Effektusok
potions:
  # Alapértelmezett érték szintenként
  STRENGTH_DEFAULT: "1.5"
  # Specifikus szintek
  STRENGTH_1: "2.0"
  STRENGTH_2: "5.0"
  STRENGTH_3: "100%" # Akár százalékot is adhatsz a 3-as szintnek
